### ISSUE TITLE
Error when I try to run

### ISSUE THREAD

**Issue by TrexKikBut** [berksaribas/vuetify-chat#19]
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in D:\Vue\chat\vuetify-chat\node_modules\@babel\helper-compilation-targets\package.json
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Vue\chat\vuetify-chat\node_modules\@babel\preset-env\lib\debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Vue\chat\vuetify-chat\node_modules\@babel\preset-env\lib\index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)

 @ multi (webpack)-dev-server/client?http://192.168.1.233:8082/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by nwtgck** [comment]
I had the same issue. I solved it using Node.js v10.18.0.

**Comment by nwtgck** [comment]
I made another solution: https://github.com/berksaribas/vuetify-chat/pull/25.
